version: '3.7'

services:
    notifyapi:
        container_name: notifyapi
        image: xrecruit/notifyapi:staging
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /var/log/notify:/workspace/logs
        ports: 
            - "8012:5000"
        environment: 
            - database=mongodb+srv://xmage:xmage@cluster0-xooqb.mongodb.net/slack_settings_test?retryWrites=true
            - base_url=http://176.9.137.77:8012/
            - origin=recruit
            - ENVIRONMENT=development 
            - to=recruit_testing@mailinator.com 
            - bcc=bcc_testing_recruit@mailinator.com
            - cc=cc_testing_recruit@mailinator.com

    mongo:
        image: mongo
        container_name: mongodb_notify



                                                                                                                                                                                                                                                                                                                                                                      