version: '3.7'

services:
    notifyapi:
        container_name: notifyapi
        image: xrecruit/notifyapi:staging
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /var/log/notify:/workspace/logs
        ports: 
            - "8006:8006"
        environment: 
            - database=mongodb://notify_staging:notify_staging@127.0.0.1:27017/notify_staging
            - base_url=http://176.9.137.77:8006/
            - origin=recruit
            - ENVIRONMENT=development 
            - to=testingattach0@gmail.com
            - bcc=bcctestingrecruit@mailinator.com
            - cc=cctestingrecruit@mailinator.com
            - oauth_url=https://slack.com/api/oauth.v2.access
            - client_id=124720392913.1351927574339
            - client_secret=456458283bbb8cdd7e4dc8edeaa77ff5

    mongo:
        image: mongo
        container_name: mongodb_notify



                                                                                                                                                                                                                                                                                                                                                                      