version: '3.7'

services:
    notifyapi:
        container_name: notifyapi
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - ./app:/workspace/app
            - /var/log/notify:/workspace/logs
        ports: 
            - "8012:5000"
        environment: 
            - base_url=http://176.9.137.77:8012/
            - to=recruit_testing@mailinator.com 
            - bcc=bcc_testing_recruit@mailinator.com
            - cc=cc_testing_recruit@mailinator.com
            - oauth_url=https://slack.com/api/oauth.v2.access
            - client_id=124720392913.1351927574339
            - client_secret=456458283bbb8cdd7e4dc8edeaa77ff5
    mongo:
        image: mongo
        container_name: mongodb_notify

