version: '3.7'

services:
    notifyapi:
        container_name: notifyapi
        image: xrecruit/notifyapi
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /var/log/notify:/workspace/logs
        ports: 
            - "8006:8006"
        environment: 
            - database=mongodb://notify_staging:notify_staging@127.0.0.1:27017/notify_staging
            - base_url=https://notifyapi.exweb.in/
            - origin=recruit
            - ENVIRONMENT=production
            - to=recruit_testing@mailinator.com 
            - bcc=bcc_testing_recruit@mailinator.com
            - cc=cc_testing_recruit@mailinator.com
            - send_grid_key=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
            - Secretkey=gUuWrJauOiLcFSDCL5TM1heITeBVcL
    mongo:
        image: mongo
        container_name: mongodb_notify

