version: '3.7'

services:
    notifyapi:
        container_name: notifyapi
        image: xrecruit/notifyapi:staging
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - /var/log/notify:/workspace/logs
        ports: 
            - "8006:8006"
        environment: 
            - database=mongodb://notify_staging:notify_staging@127.0.0.1:27017/notify_staging
            - base_url=http://176.9.137.77:8006/
            - origin=recruit
            - ENVIRONMENT=development 
            - to=recruit_testing@mailinator.com 
            - bcc=bcc_testing_recruit@mailinator.com
            - cc=cc_testing_recruit@mailinator.com

    mongo:
        image: mongo
        container_name: mongodb_notify



                                                                                                                                                                                                                                                                                                                                                                      